# .prettierrc or .prettierrc.yaml
printWidth: 80
tabWidth: 2
singleQuote: false
trailingComma: "none"
bracketSpacing: true
jsxBracketSameLine: false
parser: "babylon"
semi: true
useTabs: false
endOfLine: 'lf'

