# Database parameters
# Do not use the default user/password for safety reason
db:
  host: "127.0.0.1"
  port: 3306
  user: "streamy"
  password: "pwd1"
  database: "streamy"

session:
  secret: "pwd"

client_app:
  css: "default"
  client: "default_client"
